# nombre del actions
name: CI
# nombre que se va visualizar
run-name: ${{ github.actor }} - ${{github.event_name}}
on:
  push:
  pull_request:
    branches: [ main ]

# Lista de jobs
jobs:
  #nombre del job
  jobs-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
